Identify layer features Sample
Esri/arcgis-maps-sdk-kotlin-samples pull request #140
Opened 2023-10-24 18:15 UTC by prupani-7

## Description

PR to add a new Kotlin sample _"Identify layer features"_ in `Search and Query` category.

## Links and Data

Sample Epic: `runtime/kotlin/issues/2934`

## What To Review

-  Review the code to make sure it is easy to follow like other samples on Android
- `README.md` and `README.metadata.json` files

## How to Test

Run the sample on the sample viewer or the repo.

2023-10-27 20:35 UTC, shubham7109 requested changes
Nice sample @prupani-7! Couple comments here:

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/ComposeMapView.kt
> +        launch {
Remove `launch`
```suggestion
    LaunchedEffect(Unit) {
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/ComposeMapView.kt
> +                val identifyResult = mapView.identifyLayers(it.screenCoordinate, 12.0, false, 10)
This sample showcases the identify call in the API, let's try to use named arguments here to show which type of identify call is being used here:
```suggestion
                // call identifyLayers when a tap event occurs
                val identifyResult = mapView.identifyLayers(
                    screenCoordinate = it.screenCoordinate,
                    tolerance = 12.0,
                    returnPopupsOnly = false,
                    maximumResults = 10
                )
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/screens/MainScreen.kt
> +                ) {
The bottom row is causing a resize to both the `Row` and `ComposeMapView`, this looks janky without any transitions. A quick fix would be to set the Modifier to use `animateContentSize()`, which should help resize both elements with transitions. 

```suggestion
                ComposeMapView(
                    modifier = Modifier
                        .fillMaxSize()
                        .weight(1f)
                        .animateContentSize(),
                    mapViewModel = mapViewModel
                )
                // Bottom text to display the identify results
                Row(
                    modifier = Modifier
                        .padding(12.dp)
                        .fillMaxWidth()
                        .animateContentSize()
                ) {
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +    private val application: Application,
`application` is only used in the `init` block
```suggestion
    application: Application,
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +    val bottomTextBanner = mutableStateOf(String())
Let's set a default text message to the banner: 

```suggestion
    val bottomTextBanner = mutableStateOf("Tap on the map to identify feature layers")
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +                bottomTextBanner.value = ""
Don't think this is needed here, the `bottomTextBanner` should be set if `totalCount > 0`, else, set the text to be "Number of elements found: N/A"
```suggestion
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +                    )
The `message` would be empty if no elements are found. Maybe use a custom description for the dialog? 

```suggestion
                    messageDialogVM.showMessageDialog(
                        title = "No element found",
                        description = "Tap an area on the map with visible features"
                    )
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +data class MapViewState( // This would change based on each sample implementation
Remove comment

```suggestion
data class MapViewState( 
```

2023-10-27 20:35 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +    )
Couple nested constructors being accessed here, makes it somewhat confusing on how the viewpoint is being set. Maybe we could format it using named arguments to help better clarify the parameters: 

```suggestion
    var viewpoint: Viewpoint = Viewpoint(
        center = Point(
            x = -10977012.785807,
            y = 4514257.550369,
            spatialReference = SpatialReference(wkid = 3857)
        ),
        scale = 68015210.0
    )
```

2023-10-30 20:13 UTC, prupani-7 commented
@shubham7109 Thanks for the review suggestions! Applied. please re-review?

2023-10-30 22:11 UTC, shubham7109 approved these changes
Looks good to approve 👍

2023-10-30 22:11 UTC, shubham7109 commented on identify-layer-features/src/main/java/com/esri/arcgismaps/sample/identifylayerfeatures/components/MapViewModel.kt
> +                } else {
Could you apply this suggesstion: 
https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/pull/140#discussion_r1375016787

```suggestion
                } else {
                   bottomTextBanner.value = "Number of elements found: N/A"
```

2023-11-08 22:45 UTC, rchintapalli approved these changes
Not sure if it was part of original sample design or not, but selecting/highlighting the identified features also gives better visual experience.

Looks good to me otherwise

2023-11-09 00:16 UTC, prupani-7 commented
@rchintapalli sample design doesn't do feature selecting/highlighting. So leaving this as is. Thanks for your review.

2023-11-09 00:16 UTC, merged