Update sample - query feature table
Esri/arcgis-maps-sdk-kotlin-samples pull request #160
Opened 2023-12-20 20:43 UTC by prupani-7

## Description

PR to update the sample to use composable mapview from the toolkit

## Links and Data

Sample Epic: `runtime/kotlin/issues/3366`

## What To Review

Review updated files

## How to Test

Run the sample on the sample viewer or the repo.

2023-12-20 22:34 UTC, shubham7109 requested changes
Sample works well! Just a few minor changes to make.

2023-12-20 22:34 UTC, shubham7109 commented on query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/screens/MainScreen.kt
Replace the `application` parameter from the MainScreen with the use of `LocalContext.current.applicationContext`

2023-12-20 22:34 UTC, shubham7109 commented on query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/components/MapViewModel.kt
> +    var mapViewpointOperation: MapViewpointOperation? by mutableStateOf(null)
The `mapViewpointOperation` here does not need to be nullable, you could set it to the initial viewpoint. And remove it from the init block. 

```suggestion
    // define a mutable MapViewpointOperation and set the initial viewpoint
    var mapViewpointOperation: MapViewpointOperation by mutableStateOf(
        MapViewpointOperation.Set(usaViewpoint)
    )
```

2023-12-20 22:34 UTC, shubham7109 commented on query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/components/MapViewModel.kt
> +                // update the MapViewpointOperation to set the geometry of the returned feature
"set the geometry of the returned feature" doesn't sound right to me here. Maybe the comment could be: 

```suggestion
                // update the viewpoint to the bounding geometry of the returned feature
```

2023-12-20 22:34 UTC, shubham7109 commented on query-feature-table/src/main/java/com/esri/arcgismaps/sample/queryfeaturetable/components/MapViewModel.kt
Extra line here

2023-12-21 21:53 UTC, prupani-7 commented
@shubham7109 Applied the suggestions, thanks! a re-review?

2023-12-21 23:41 UTC, shubham7109 approved these changes

2023-12-22 21:32 UTC, changanxian approved these changes
👍

2023-12-23 01:28 UTC, merged