Trev8939/configure basemap style parameters
Esri/arcgis-maps-sdk-kotlin-samples pull request #200
Opened 2024-05-23 11:03 UTC by TADraeseke

## Description
PR to add a new Kotlin sample  "Configure basemap style parameters" in the Maps category.
## Links and Data
Sample issue: `runtime/kotlin/issues/3847`
## What To Review
-  Correct composable patterns
-  Review the code to make sure it is easy to follow like other samples on Android
- `README.md` and `README.metadata.json` files
## How to Test
Run the sample from this branch

2024-05-23 12:10 UTC, hud10837 requested changes
Works great and easy to understand. I have a few points that might make this a little more idiomatic

2024-05-23 14:13 UTC, TADraeseke commented on configure-basemap-style-parameters/README.md
> +
I think I'll leave this out for now. The README is above on other platforms and diverging from them is not preferred

2024-05-23 14:13 UTC, TADraeseke commented
Thanks very much for that review @hud10837! Ready for re-review

2024-05-27 07:45 UTC, hud10837 approved these changes
👍 Looks good, easy to understand

2024-05-29 01:09 UTC, shubham7109 reviewed
Instead of disabling the `LanguageStrategyControls` I would suggest to disable the `SpecificLanguageControls` if "Local" strategy is used (except None). Or maybe auto-select "Global" if the user decides to choose a specific language. 

Using this, we can avoid the scenario if the user was to choose "Local" strategy and choose a specific language. Which doesn't look right to in my opinion.

![Screenshot 2024-05-28 at 5 58 51 PM](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/assets/14892474/1f6a1dd2-38ed-47e9-932f-788343f39615)


Sample looks good, added some general feedback comments. Nice work @TADraeseke 👍

2024-05-29 01:09 UTC, shubham7109 commented on configure-basemap-style-parameters/src/main/java/com/esri/arcgismaps/sample/configurebasemapstyleparameters/screens/MainScreen.kt
> +                                    Column {
You could skip using a divider and split the two columns down the middle: 

```suggestion
                                Row(horizontalArrangement = Arrangement.SpaceBetween) {
                                    Column(Modifier.weight(0.5f)) {
                                        // UI for setting the language strategy
                                        LanguageStrategyControls(
                                            languageStrategyOptions = mapViewModel.languageStrategyOptions,
                                            onLanguageStrategyChange = { languageStrategy ->
                                                mapViewModel.updateLanguageStrategy(languageStrategy)
                                            },
                                            languageStrategy = mapViewModel.languageStrategy,
                                            enabled = (mapViewModel.specificLanguage == "None")
                                        )
                                    }

                                    Column(Modifier.weight(0.5f)) {
```

2024-05-30 17:09 UTC, puneet-pdx commented
@TADraeseke I can review/approve this when you are done addressing @shubham7109 comments.

2024-05-31 09:16 UTC, TADraeseke commented
> Instead of disabling the `LanguageStrategyControls` I would suggest to disable the `SpecificLanguageControls` if "Local" strategy is used (except None). Or maybe auto-select "Global" if the user decides to choose a specific language.
> 
> Using this, we can avoid the scenario if the user was to choose "Local" strategy and choose a specific language. Which doesn't look right to in my opinion.
> 
> ![Screenshot 2024-05-28 at 5 58 51 PM](https://private-user-images.githubusercontent.com/14892474/334614297-1f6a1dd2-38ed-47e9-932f-788343f39615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDY5OTgsIm5iZiI6MTcxNzE0NjY5OCwicGF0aCI6Ii8xNDg5MjQ3NC8zMzQ2MTQyOTctMWY2YTFkZDItMzhlZC00N2U5LTkzMmYtNzg4MzQzZjM5NjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMmFiNTRiNzAxMjY1ZTk2MGE4MjNhYWNiMDMyYzA4NDczODkzYWRkMDU5ZTc2MDI5OTliZGI4NGJjM2IxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T4m4rl2FISd3lBrEDL0cabCqpPeBvWQTTvhBdeHkHmE)
> 
> Sample looks good, added some general feedback comments. Nice work @TADraeseke 👍

Thanks @shubham7109 -- disabling the language strategy controls, as seen in this sample, was set out in the common samples design. https://devtopia.esri.com/runtime/common-samples/tree/main/designs/ConfigureBasemapStyleParameters#how-it-works

Not sure if we want to go back and suggest inverting that UI behaviour at this stage? Could be a good one for the samples council I guess!

2024-05-31 09:17 UTC, TADraeseke commented
> @TADraeseke I can help review/approve this when you are done addressing @shubham7109 comments.

Thanks @puneet-pdx! Shubham is actually the second reviewer on this one already, but I've just opened another PR for a new sample that I'd be grateful for your review on if you're keen! https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/pull/204

2024-05-31 21:06 UTC, puneet-pdx commented
@TADraeseke I was trying to help finish this review in this sprint as @shubham7109 is out for the next week. If you want @shubham7109 to approve this then I will hold back.

2024-06-03 20:20 UTC, puneet-pdx approved these changes
@TADraeseke some minor comments. Looks good overall.

2024-06-04 12:51 UTC, TADraeseke commented
Thanks @puneet-pdx! Made those fixes. Merging!

2024-06-04 12:51 UTC, merged