Nour/generate offline map compose
Esri/arcgis-maps-sdk-kotlin-samples pull request #219
Opened 2024-07-11 20:38 UTC by NourdotSiwar

## Description

## Links and Data

## What To Review

## How to Test

2024-07-19 17:20 UTC, shubham7109 requested changes
Nice work @NourdotSiwar, I added a few comments and change requests. 👍

2024-07-22 21:25 UTC, shubham7109 requested changes
Final list of change requests, and the Compose sample looks good. Should be good to approve after this!

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/README.md
On line `17` could you update step 1 to use: "`PoralItem`" instead of "`Portal` item"

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/README.md
> +The creation of the offline map can be fine-tuned using [parameter overrides for feature layers](https://github.com/Esri/arcgis-runtime-samples-android/tree/master/java/generate-offline-map-overrides
We do not have these samples yet, let's remove the URLs pointing to the runtime repo and just have plain text here.  Add an issue to the backlog to update this section when the two samples are implemented in the future.

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/README.metadata.json
> +    ],
We shouldn't add redirects from Runtime to Maps SDK. Redirects would be helpful when the currently published sample would be renamed to a different name, so we should redirect from old sample name. Not needed here.

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +                    Log.i("Progress", "offlineMapJobProgress: ${offlineMapJobProgress.intValue}")
Not needed :) 
```suggestion
```

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +                    map = it.offlineMap
A comment here would be helpful: 
```suggestion
                    // set the offline map result as the displayed map
                    map = it.offlineMap
```

2024-07-22 21:25 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +            viewModelScope.launch {
Not a required change, but when it comes to launching multiple coroutine scopes the `with` property could be helpful:

```kotlin
with(viewModelScope) {
    launch {
        // Collect Progress
    }
    launch {
        // Wait for Job result
    }
}
```

2024-07-23 22:47 UTC, shubham7109 commented on generate-offline-map/README.md
Seems like this file now has changes that shouldn't be needed. Use the "Files changed" tab to visualize the diff of the changes you are proposing to `v.next`. In the README.md we shouldn't be formatting this to Android studio's line length since it not really a code file. These changes may impact the description shown on developer [pages](https://developers.arcgis.com/kotlin/sample-code/generate-offline-map/).

Please revert these changes back to use the original README instructions, with the compose-specific changes.

2024-07-23 23:12 UTC, shubham7109 approved these changes
Looks great, this sample migrated to Compose will be very helpful for users, nice work @NourdotSiwar! 🎉

2024-07-29 11:26 UTC, TADraeseke commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +            title = "Could not get geometry of the downloadArea"
```suggestion
            title = "Could not get geometry of the download area"
```

2024-07-29 11:27 UTC, TADraeseke commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +                launch {
```suggestion
                launch(Dispatchers.IO) {
```

2024-07-29 11:28 UTC, TADraeseke commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +                        graphicsOverlay.graphics.clear()
```suggestion
                        // Set the offline map result as the displayed map and clear the red bounding box graphic
                        map = it.offlineMap
                        graphicsOverlay.graphics.clear()
```

2024-07-29 11:28 UTC, TADraeseke commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +    val showJobProgressDialog = mutableStateOf(false)
could be another good one for a `by`

2024-07-29 11:30 UTC, TADraeseke commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +    val offlineMapJobProgress = mutableIntStateOf(0)
by here too

2024-07-30 08:52 UTC, TADraeseke approved these changes
LGTM! Using the Dispatchers here shows good understanding of coroutines and how to make them run efficiently. In a sample context they're also good reinforcement to our user devs that "this block of code is doing long running network work" or "this block of code is updating the UI". Good work!

2024-07-30 15:50 UTC, merged