Migrate Edit and Sync Features with Feature Service to Compose
Esri/arcgis-maps-sdk-kotlin-samples pull request #227
Opened 2024-07-25 21:45 UTC by NourdotSiwar

## Description
PR to migrate an XML Kotlin sample _"Edit and Sync Features with Feature Service to Compose"_ in `Edit and Manage Data` category.

## Links and Data
Sample Epic: `runtime/kotlin/issues/ISSUE_NUMBER`
- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/

## What To Review
-  Review the code to make sure it is easy to follow like other samples on Android
- `README.md` and `README.metadata.json` files

## How to Test
Run the sample on the sample viewer or the repo.

2024-07-29 11:01 UTC, TADraeseke requested changes
Nice one @NourdotSiwar! Hopped on a second review here since I saw it in the US board. Alot going on in this sample and you've made it really readable! See comments below. Thanks!

2024-07-29 11:08 UTC, TADraeseke commented
Ahh sorry @NourdotSiwar and @shubham7109 -- I meant to grab one of the ones in ready to review 2. Apologies!

2024-07-30 09:31 UTC, TADraeseke approved these changes
LGTM! Just one further comment in line.

Also, I think the screenshot needs updating. Good to remove the "For Developer Use Only" watermark. Lately I've been using a Pixel Fold emulator for screenshots. Resizing to a width of 700 pixels, and then cutting off the top of the map at 400 pixels height. That way I don't need to worry about cutting out the toolbar at the top with the title

2024-07-30 09:31 UTC, TADraeseke commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +        )
Could put this in an .apply block on the creation of the map on line 73

2024-08-01 20:24 UTC, shubham7109 requested changes
Nice work @NourdotSiwar! 🎉 

I added some code quality changes, and noticed a screenshot placed in the wrong sample probably by accident. And added a comment to help optimize the usage of different coroutine dispatchers.

2024-08-01 20:24 UTC, shubham7109 commented on show-viewshed-from-point-in-scene/src/main/res/drawable/image.png
This screenshot seems to be in the `show-viewshed-from-point-in-scene` sample. This would need to be removed.

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/screens/MainScreen.kt
> +                        .padding(0.dp),
Not sure why it's explicitly `0.dp` padding here, let's use a generous padding here like your generate offline map UI.
```suggestion
                        .padding(12.dp),
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/screens/MainScreen.kt
> +                        },
```suggestion
                        onClick = mapViewModel::onClickActionButton,
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +    val messageDialogVM: MessageDialogViewModel = MessageDialogViewModel()
Could be simplified: 

```suggestion
    val messageDialogVM = MessageDialogViewModel()
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +            // If the metadata load fails, show the error and return
```suggestion
            // If the geodatabase sync from feature service fails to load, show the error and return
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +        }
Nothing wrong with using an addition-assignment operator here, but I would suggest using `.addAll` operation from Kotlin Collections instead to help with the code readability: 

```suggestion
            map.operationalLayers.addAll(
                geodatabase.featureTables.map { featureTable ->
                    FeatureLayer.createWithFeatureTable(featureTable)
                }
            )
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +            syncGeodatabaseParameters.layerOptions +=
Same as above: 

```suggestion
            syncGeodatabaseParameters.layerOptions.addAll(
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/java/com/esri/arcgismaps/sample/editandsyncfeatureswithfeatureservice/components/MapViewModel.kt
> +            }
In this code block (`with(viewModelScope)`) you launch a `launch(Dispatchers.IO)` and then it seems like inside this coroutine scope you launch a `launch(Dispatchers.Main)` to collect job's progress. Nested usage of different dispatchers would not run the coroutines as you have defined. 

I would suggest to remove the `createSyncGeodatabaseJob` and the setting of the `showSyncGeodatabaseJobProgressDialog` and `syncGeodatabaseJob.start()` to be placed outside outside the coroutine scope. As none of these are suspended calls and don't need to be defined in a launched scope. And only use suspend function calls within your launched coroutines: 
- launch(Dispatchers.Main) to collect job's progress
- launch(Dispatchers.IO) to await the job's result 

```suggestion
            syncGeodatabaseJob = geodatabaseSyncTask.createSyncGeodatabaseJob(
                parameters = syncGeodatabaseParameters,
                geodatabase = geodatabase
            )

            syncGeodatabaseJob?.let { syncGeodatabaseJob ->

                // Show the dialog
                showSyncGeodatabaseJobProgressDialog = true

                // Start the job and wait for Job result
                syncGeodatabaseJob.start()

                with(viewModelScope) {
                    // Create the SyncGeodatabaseJob using the parameters and the geodatabase
                    launch(Dispatchers.IO) {
                        syncGeodatabaseJob.result().onSuccess {
                            showSuccessMessage("Sync Complete")
                        }.onFailure {
                            messageDialogVM.showMessageDialog("Database did not sync correctly")
                        }

                        // Dismiss the dialog
                        showSyncGeodatabaseJobProgressDialog = false

                        // Set the edit state to indicate geodatabase is ready for edits
                        geodatabaseEditState = GeodatabaseEditState.READY
                    }

                    // Create a flow-collection for the job's progress
                    launch(Dispatchers.Main) {
                        syncGeodatabaseJob.progress.collect { progress ->
                            // Display the current job's progress value
                            syncGeodatabaseJobProgress = progress
                        }
                    }
                }
            }
```

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/res/values/strings.xml
> +    <string name="dialog_title">Fetching result</string>
This string is not used.

2024-08-01 20:24 UTC, shubham7109 commented on edit-and-sync-features-with-feature-service/src/main/res/values/strings.xml
> +    <string name="reset_operation">Reset</string>
This string is not used.

2024-08-03 00:28 UTC, shubham7109 approved these changes
Looks good 👍 

Tested with a local sample viewer build. Merging this in to `v.next`.

2024-08-03 00:28 UTC, merged