Fixed issue through adding onLayerViewStatechanged on MapView
Esri/arcgis-maps-sdk-kotlin-samples pull request #232
Opened 2024-08-09 18:54 UTC by NourdotSiwar

## Description
PR to fix a Kotlin sample _"GENERATE_OFFLINE_MAP"_ in `EDIT_AND_MANAGE_DATA` category.
## Links and Data
Sample Epic: `runtime/kotlin/issues/ISSUE_NUMBER`
- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/
## What To Review
-  Review the changed/added code to make sure the changes wouldn't impact anything else and to see if sample code is easy to read.
- `MainScreen.kt` and `MapViewModel.kt` files

## How to Test
Run the sample on the sample viewer or the repo. 
1. When running it, the red border should always show on launch
2. After generating the offline map, and resettiing the map, the red border should show and stay the same size.

2024-08-13 17:40 UTC, shubham7109 requested changes
Nice fix @NourdotSiwar, I believe this was an issue with our previous SV as well. Few general comments, and it should be good to approve.

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/screens/MainScreen.kt
> +                            println("Size: $size")
Remove line:

```suggestion
```

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +    var currentSpatialReference by mutableStateOf<SpatialReference?>(null)
I'm not able to understand the need for this added line. It seems like it is set via the MainScreen:
```kotlin
 onSpatialReferenceChanged = { spatialReference ->
                        mapViewModel.currentSpatialReference = spatialReference
                    }
```
But this assignment is not utilized anywhere else.

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> -        // Use the points to define and return an envelope
Maybe use a comment here like:
```kotlin
// Create an envelope to set the download area's geometry using the defined bounds

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/components/MapViewModel.kt
> +
Remove line
```suggestion
```

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/screens/MainScreen.kt
> +                        // Ensure the map is fully loaded before calculating the download area
Wording suggestion: 

```suggestion
                        // On launch, ensure the map is loaded before calculating the download area
```

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/screens/MainScreen.kt
> +                        // Ensure the map is fully loaded before calculating the download area
```suggestion
                        // Ensure the map is loaded before calculating the download area
```

2024-08-13 17:40 UTC, shubham7109 commented on generate-offline-map/src/main/java/com/esri/arcgismaps/sample/generateofflinemap/screens/MainScreen.kt
> +
Remove line
```suggestion
```

2024-08-15 00:31 UTC, saratchandrakarumuri commented
Looking good and GO is consistently rendered as expected

2024-08-15 00:31 UTC, saratchandrakarumuri approved these changes

2024-08-15 00:42 UTC, merged