[Patch] Revoke OAuth tokens at sample start
Esri/arcgis-maps-sdk-kotlin-samples pull request #239
Opened 2024-10-10 10:59 UTC by 01smito01

## Description
Change "Show portal user info" and "Authenticate with OAuth" to remove any cached authentication from `ArcGISEnvironment`. This makes them behave properly in the sample viewer even after a user has authenticated in another sample 

## Links and Data
Sample Epic: [#4755](https://devtopia.esri.com/runtime/kotlin/issues/4755)
- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/) Job for this PR has been run
  - [x] link: [Yes](https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/47/)
## What To Review
-  Do the samples now behave as expected in the sample viewer?
- Is `runBlocking` the best way to implement this?

## How to Test
Run the samples in the sample viewer. Do they present an authentication challenge after completing one in another sample?

2024-10-14 08:47 UTC, gunt0001 requested changes

2024-10-14 08:47 UTC, gunt0001 commented on authenticate-with-oauth/src/main/java/com/esri/arcgismaps/sample/authenticatewithoauth/MainActivity.kt
> +
It's not recommended to use `runBlocking` in production code. The alternative here is to launch a coroutine on the Main dispatcher, then tdo the sign out followed by displaying the app:
```suggestion
        lifecycleScope.launch(Dispatchers.Main) {
            // Sign out of any portals which are already authenticated
            ArcGISEnvironment.authenticationManager.signOut()

            setContent {
                SampleAppTheme {
                    AuthenticateWithOAuthApp()
                }
            }
        }
```

Same change would need to be made to Show Portal User Info & Create And Save Map samples.

2024-10-14 08:47 UTC, gunt0001 commented on authenticate-with-oauth/src/main/java/com/esri/arcgismaps/sample/authenticatewithoauth/MainActivity.kt
Should the API key also be nulled out here, same as you did in [Create And Safe Map](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/blob/v.next/create-and-save-map/src/main/java/com/esri/arcgismaps/sample/createandsavemap/MainActivity.kt#L38-L40) sample?

2024-10-14 08:47 UTC, gunt0001 commented on show-portal-user-info/src/main/java/com/esri/arcgismaps/sample/showportaluserinfo/MainActivity.kt
>          ArcGISEnvironment.apiKey = ApiKey.create(BuildConfig.API_KEY)
Should we be setting an API key here, since the sample uses a named user?

\cc @shubham7109

2024-10-16 01:14 UTC, shubham7109 commented
This PR will be replaced with https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/pull/244 to apply these changes on the SV level.

2024-10-21 15:39 UTC, 01smito01 commented
Closing as https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/pull/244 should be done this release. Will draft a new PR for removing the existing workflow from Create & Save Map.

2024-10-21 15:39 UTC, closed without merging