Simple fix to not re-running load
Esri/arcgis-maps-sdk-kotlin-samples pull request #248
Opened 2024-10-23 23:06 UTC by TADraeseke

Explored dependency injection, which would require importing dagger/hilt and is probably beyond min ship.

How's this for a simple check to prevent repeat calls to load logic?

2024-10-24 15:49 UTC, shubham7109 commented
I would maybe recommend using this logic in the MainActivity, to be clear that `load` is only meant to run once per app session. 
```kotlin
var isInitialized by rememberSaveable { mutableStateOf(false) }
LaunchedEffect(Unit) {
    if (!isInitialized) {
        DefaultSampleInfoRepository.load(context)
        isInitialized = true
    }
}
```

2024-10-24 19:07 UTC, shubham7109 approved these changes
LGTM 👍

2024-10-25 19:11 UTC, sorenoid requested changes
LGTM, Two small suggestions to consider.

2024-10-25 19:11 UTC, sorenoid commented on app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/DefaultSampleInfoRepository.kt
> +            val json = Json { ignoreUnknownKeys = true }
This should be initialized as a property outside of the function because it is an expensive call and thus a simple performance improvement.

2024-10-25 19:11 UTC, sorenoid commented on app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/SampleViewerApplication.kt
> +        runBlocking {
this will block the main thread at app launch. Better to launch this, as you had it before.

2024-10-25 21:08 UTC, TADraeseke commented on app/src/main/java/com/esri/arcgismaps/kotlin/sampleviewer/model/DefaultSampleInfoRepository.kt
> +    private var isInitialized = false
Hmm, this was already in place. Not sure why it didn't come through

2024-10-25 21:13 UTC, TADraeseke commented
Apologies for missing your earlier comment on instantiating the json object.

Ready for re-review @sorenoid!

2024-10-28 17:47 UTC, merged