Migrate Find route
Esri/arcgis-maps-sdk-kotlin-samples pull request #271
Opened 2024-11-16 01:04 UTC by shubham7109

## Description
PR to migrate the Find route sample to Compose

## Links and Data

## What To Review

## How to Test

2025-01-13 19:30 UTC, TADraeseke requested changes
Really good clean code! Few small comments below.

One high level thought--should we grey out or even remove the "Solve route directions" button after solving?

2025-01-13 20:26 UTC, shubham7109 commented
@TADraeseke I added in the feedback comments, ready for your review. 

Regarding the solve route button, I had intentionally kept it enabled to allow for repeated route solves which then updates the map's viewpoint to the result. If you find it unintuitive, I can disable the button after the first solve.

2025-01-13 20:29 UTC, TADraeseke approved these changes
LGTM!

2025-01-15 21:03 UTC, sorenoid approved these changes

2025-01-15 22:37 UTC, merged