Colinanderson/play kml tour compose
Esri/arcgis-maps-sdk-kotlin-samples pull request #287
Opened 2024-12-04 14:23 UTC by colinanderson

## Description

Change the play KML tour sample to a compose implementation

## Links and Data

## What To Review

## How to Test

2024-12-05 18:09 UTC, TADraeseke requested changes
Looking good @colinanderson -- just some small things below

2024-12-05 18:09 UTC, TADraeseke commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/components/PlayKMLTourViewModel.kt
> +        ArcGISScene(BasemapStyle.ArcGISImagery).apply {
can probably bump this up a line

2024-12-05 18:09 UTC, TADraeseke commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/components/PlayKMLTourViewModel.kt
> +    val statusFlow = _statusFlow.asStateFlow()
could these maybe more explictly named? This code gets read outside of an IDE on the website, so more verbose names can be helpful

_tourStatus or _tourStatusFlow maybe?

2024-12-05 18:09 UTC, TADraeseke commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/screens/PlayKMLTourScreen.kt
> +                    }) {
We normally make the chain of modifer.padding.fill.etc.etc vertically so more like this:

```suggestion
                LinearProgressIndicator(
                progress = { progressFlow }, modifier = Modifier
                    .fillMaxWidth()
                    .padding(all = padding)
            )
            Text(
                "${stringResource(R.string.tour_status)} ${tourStateToString(stateFlow)}",
                modifier = Modifier
                    .padding(all = padding)
                    .align(Alignment.CenterHorizontally)
            )
            Row(
                modifier = Modifier.fillMaxWidth()
            ) {
                Button(enabled = (stateFlow == KmlTourStatus.Paused || stateFlow == KmlTourStatus.Playing),
                    modifier = Modifier
                        .fillMaxWidth(0.5f)
                        .padding(all = padding),
                    onClick = {
                        viewModel.reset()
                    }) {
```

2024-12-10 13:09 UTC, colinanderson commented
@TADraeseke that should be all your comments addressed.

2024-12-10 17:41 UTC, TADraeseke approved these changes
LGTM!

2024-12-11 16:08 UTC, colinanderson commented
Updated the enable/disable of the play button to disable when the tour is not initialised. Also renamed classes from `KML` to` Kml` and some other renames based on https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/pull/287#discussion_r1871864445.

New vTest - https://runtime-kotlin.esri.com/view/all/job/vtest/job/sampleviewer/62

2024-12-11 17:14 UTC, 01smito01 approved these changes
Looks good, just a few suggestions.

2024-12-11 18:20 UTC, colinanderson commented on samples/play-kml-tour/README.metadata.json
> +}
Added

2024-12-11 18:20 UTC, colinanderson commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/components/PlayKmlTourViewModel.kt
> +                }
Changed this and another `if` to be more Kotlin style.

2024-12-11 18:20 UTC, colinanderson commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/screens/PlayKmlTourScreen.kt
> +import androidx.compose.ui.unit.dp
Done

2024-12-11 18:21 UTC, colinanderson commented on samples/play-kml-tour/src/main/java/com/esri/arcgismaps/sample/playkmltour/screens/PlayKmlTourScreen.kt
> +    val kmlTourProgress by kmlTourProgressFlow.collectAsStateWithLifecycle(0.0f)
Changed as discussed.

2024-12-11 18:23 UTC, colinanderson commented
@01smito01 I made some updates so please take another look - interested if the `let` usages are an improvement or not.

2024-12-12 09:58 UTC, 01smito01 approved these changes
I'm ambivalent on whether the `let`s are improvements, but I like the `when`. Everything else looks fine.

2024-12-12 15:44 UTC, merged