Display dimensions
Esri/arcgis-maps-sdk-kotlin-samples pull request #67
Opened 2023-02-22 22:16 UTC by shubham7109

## Description
PR to add a new Kotlin sample _"Display dimensions"_ in `Layers` category. This sample displays dimension features from a mobile map package.

## Links and Data
Sample Epic: `runtime/kotlin/issues/1939 `

## What To Review
-  Review the code to make sure it is easy to follow like other samples on Android
- `README.md` and `README.metadata.json` files

2023-02-27 23:58 UTC, prupani-7 requested changes
@shubham7109 The sample works well! 

Added a few comments.

2023-02-27 23:58 UTC, prupani-7 commented on display-dimensions/src/main/java/com/esri/arcgismaps/sample/displaydimensions/MainActivity.kt
> +import com.arcgismaps.mapping.ArcGISMap
there are some unused imports here

2023-02-27 23:58 UTC, prupani-7 commented on display-dimensions/src/main/java/com/esri/arcgismaps/sample/displaydimensions/MainActivity.kt
> +        val mobileMapPackage = MobileMapPackage("$provisionPath/Edinburgh_Pylon_Dimensions.mmpk")
we could move this string to string.xml

2023-02-27 23:58 UTC, prupani-7 commented on display-dimensions/src/main/java/com/esri/arcgismaps/sample/displaydimensions/MainActivity.kt
> +    // track if the layer is enabled
these would be separated by an empty line... Ran reformat Code in AS

2023-02-28 00:01 UTC, prupani-7 commented on display-dimensions/README.md
> +When the sample loads, it will automatically display the map containing dimension features from the mobile map package. The name of the dimension layer containing the dimension features is displayed
"Dimension settings" button

2023-02-28 00:31 UTC, shubham7109 commented
Thanks @prupani-7  Added in the feedback

2023-02-28 00:41 UTC, prupani-7 approved these changes
LGTM!

2023-02-28 13:24 UTC, hud10837 approved these changes
Sample looks good, just one question but no need to re-review

2023-02-28 13:24 UTC, hud10837 commented on display-dimensions/src/main/java/com/esri/arcgismaps/sample/displaydimensions/MainActivity.kt
> +                    isDimensionLayerEnabled = isEnabled
Could these just go in the apply blocks where you initialize `dimensionLayerSwitch`? Same for `definitionSwitch.setOnCheckedChangeListener`

2023-02-28 13:24 UTC, hud10837 commented on display-dimensions/src/main/AndroidManifest.xml
> +</manifest>
Missing newline

2023-02-28 18:25 UTC, merged